/* eslint-disable max-len */
module.exports = {
  hubID: "406966876367749131",
  messages: {
    prefix: "ei$"
  },
  maintenance: true,
  buildVersion: {
    number: "v2",
    name: "`Woah`"
  },
  files: {
    commands: "./commands",
    events: "./events",
    logs: "./logs"
  },
  mdb: {
    blacklist: "blacklist",
    donations: "donations",
    guilds: "guilds",
    afk: "afk"
  },
  lang: {
    underMaintenance: "Oh no, my code's being updated, please check back later! (Sorry but Echo is under maintenance right now)",
    helpMsgs: [
      /* Goomig */
      "Help is flying through the sky, into your DMs!", "Help is sliding on ice, into your DMs!",
      /* Dwigoric */
      "Sending 911 under your doormat!", "Delivering the savory pizza in front of your door!", "Sending angels into your mailbox!", "Hooman, I have heeded your request for help.", "So help me God", "Helping you get out of your problems...", "Magic stones, ye say? Right here under the kilt.", "Helping you escape the shadow realm...", "Let me check that I have this right...",
      /* Goomig */
      "Whoops, Slip, SQUASH THAT REQUEST FOR HELP HERE I COME!",
      /* Dwigoric */
      "I am really sorry to hear that. Is there anything I can do to do for your request for help?", "That is a good question. Find it out yourself.", "I'm not sure, but don't ask me for help.", "I'm sorry, I don't have the information on that. May I put you on hold for a few minutes? I will clarify this with our manager.", "I'm sorry, this question would be out of my expertise, but Daniel from the tech support department will be able to help you. Would you like me to connect you with him?", "May I put your call on hold while I am checking your order?", "I'm sorry, Echo is not available right now. May I help you with something?", "I'm sorry, we don't have this feature at the moment. We do intend to add it to our service and we can notify you when it has been done. Would you like to receive an email update?",
      /* Wistful */
      "YA NEED HELP?",
      /* Fiery_Hacker */
      "Bringing in the reinforcements..."
    ],
    fixed: {
      false: "False",
      true: "True",
      online: "Online",
      dnd: "Do Not Disturb",
      idle: "Idle",
      offline: "Offline"
    },
    langCodes: {
      afrikaans: "af",
      albanian: "sq",
      amharic: "am",
      arabic: "ar",
      armenian: "hy",
      azeerbaijani: "az",
      basque: "eu",
      belarusian: "be",
      bengali: "bn",
      bosnian: "bs",
      bulgarian: "bg",
      catalan: "ca",
      ebuano: "ceb",
      simplified_chinese: "zh-CN",
      traditional_chinese: "zh-TW",
      corsican: "co",
      croatian: "hr",
      czech: "cs",
      danish: "da",
      dutch: "nl",
      english: "en",
      esperanto: "eo",
      estonian: "et",
      finnish: "fi",
      french: "fr",
      frisian: "fy",
      galician: "gl",
      georgian: "ka",
      german: "de",
      greek: "el",
      gujarati: "gu",
      haitian_creole: "ht",
      hausa: "ha",
      hawaiian: "haw",
      hebrew: "iw",
      hindi: "hi",
      hmong: "hmn",
      hungarian: "hu",
      icelandic: "is",
      igbo: "ig",
      indonesian: "id",
      irish: "ga",
      italian: "it",
      japanese: "ja",
      javanese: "jw",
      kannada: "kn",
      kazakh: "kk",
      khmer: "km",
      korean: "ko",
      kurdish: "ku",
      kyrgyz: "ky",
      lao: "lo",
      latin: "la",
      latvian: "lv",
      lithuanian: "lt",
      luxembourgish: "lb",
      macedonian: "mk",
      malagasy: "mg",
      malay: "ms",
      malayalam: "ml",
      maltese: "mt",
      maori: "mi",
      marathi: "mr",
      mongolian: "mn",
      myanmar: "my",
      nepali: "ne",
      norwegian: "no",
      nyanja: "ny",
      pashto: "ps",
      persian: "fa",
      polish: "pl",
      portuguese: "pt",
      punjabi: "pa",
      romanian: "ro",
      russian: "ru",
      samoan: "sm",
      scots_gaelic: "gd",
      serbian: "sr",
      sesotho: "st",
      shona: "sn",
      sindhi: "sd",
      sinhala: "si",
      slovak: "sk",
      slovenian: "sl",
      somali: "so",
      spanish: "es",
      sundanese: "su",
      swahili: "sw",
      swedish: "sv",
      tagalog: "tl",
      tajik: "tg",
      tamil: "ta",
      telugu: "te",
      thai: "th",
      turkish: "tr",
      ukrainian: "uk",
      urdu: "ur",
      uzbek: "uz",
      vietnamese: "vi",
      welsh: "cy",
      xhosa: "xh",
      yiddish: "yi",
      yoruba: "yo",
      zulu: "zu"
    }
  },
  colors: {
    orange: "#F4862C",
    red: "#F2524A",
    green: "#92EE8F",
    blue: "#7289DA"
  },
  owners: ["147891648628654082"]
};